version: 2
sources:
    - name: source
      database: MYDB
      schema: BRONZE
      tables:
        - name: STORES_SOURCE
    - name: xfm
      database: MYDB
      schema: SILVER
      tables:
        - name: Walmart_store_dim